services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82
        networks:
            - nginx-php82-mysql8
    php82:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        container_name: php82-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php82-mysql8
    database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        volumes:
            - database_data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
        networks:
            - nginx-php82-mysql8
networks:
    nginx-php82-mysql8:
volumes:
    database_data: